[22_5_2018_15:27:36] {SEVERE} CONNECTIONDB - java.sql.SQLException: Access denied for user '<your-own-db-user>'@'localhost' (using password: YES)	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:569)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:537)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:527)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1634)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:637)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:351)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:224)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.telegram.plugins.echo.database.ConnectionDB.openConexion(ConnectionDB.java:31)
	at org.telegram.plugins.echo.database.ConnectionDB.<init>(ConnectionDB.java:24)
	at org.telegram.plugins.echo.database.DatabaseManagerImpl.<init>(DatabaseManagerImpl.java:32)
	at org.telegram.Deepthought.main(Deepthought.java:39)

[22_5_2018_15:30:3] {SEVERE} CONNECTIONDB - java.sql.SQLException: The server time zone value '�й���׼ʱ��' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:569)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:537)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:527)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:512)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:480)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:498)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:494)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:69)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1634)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:637)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:351)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:224)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.telegram.plugins.echo.database.ConnectionDB.openConexion(ConnectionDB.java:31)
	at org.telegram.plugins.echo.database.ConnectionDB.<init>(ConnectionDB.java:24)
	at org.telegram.plugins.echo.database.DatabaseManagerImpl.<init>(DatabaseManagerImpl.java:32)
	at org.telegram.Deepthought.main(Deepthought.java:39)

[22_5_2018_15:30:32] {SEVERE} CONNECTIONDB - java.sql.SQLException: The server time zone value '�й���׼ʱ��' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:569)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:537)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:527)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:512)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:480)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:498)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:494)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:69)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1634)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:637)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:351)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:224)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.telegram.plugins.echo.database.ConnectionDB.openConexion(ConnectionDB.java:31)
	at org.telegram.plugins.echo.database.ConnectionDB.<init>(ConnectionDB.java:24)
	at org.telegram.plugins.echo.database.DatabaseManagerImpl.<init>(DatabaseManagerImpl.java:32)
	at org.telegram.Deepthought.main(Deepthought.java:39)

[22_5_2018_15:32:25] {SEVERE} CONNECTIONDB - java.sql.SQLException: The server time zone value '�й���׼ʱ��' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:569)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:537)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:527)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:512)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:480)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:498)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:494)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:69)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1634)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:637)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:351)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:224)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.telegram.plugins.echo.database.ConnectionDB.openConexion(ConnectionDB.java:31)
	at org.telegram.plugins.echo.database.ConnectionDB.<init>(ConnectionDB.java:24)
	at org.telegram.plugins.echo.database.DatabaseManagerImpl.<init>(DatabaseManagerImpl.java:32)
	at org.telegram.Deepthought.main(Deepthought.java:39)

[22_5_2018_15:33:9] {SEVERE} CONNECTIONDB - java.sql.SQLException: The server time zone value '�й���׼ʱ��' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:569)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:537)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:527)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:512)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:480)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:498)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:494)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:69)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1634)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:637)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:351)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:224)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.telegram.plugins.echo.database.ConnectionDB.openConexion(ConnectionDB.java:31)
	at org.telegram.plugins.echo.database.ConnectionDB.<init>(ConnectionDB.java:24)
	at org.telegram.plugins.echo.database.DatabaseManagerImpl.<init>(DatabaseManagerImpl.java:32)
	at org.telegram.Deepthought.main(Deepthought.java:39)

[22_5_2018_15:36:23] {SEVERE} CONNECTIONDB - java.sql.SQLException: The server time zone value '�й���׼ʱ��' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:569)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:537)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:527)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:512)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:480)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:498)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:494)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:69)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1634)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:637)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:351)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:224)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.telegram.plugins.echo.database.ConnectionDB.openConexion(ConnectionDB.java:31)
	at org.telegram.plugins.echo.database.ConnectionDB.<init>(ConnectionDB.java:24)
	at org.telegram.plugins.echo.database.DatabaseManagerImpl.<init>(DatabaseManagerImpl.java:32)
	at org.telegram.Deepthought.main(Deepthought.java:39)

[22_5_2018_15:38:5] {INFO} DATABASEMANAGER - Current db version: 0
[22_5_2018_15:38:11] {INFO} KERNELMAIN - --------------KERNEL CREATED--------------
[22_5_2018_15:38:11] {WARNING} KernelPersistence - Loaded state in 0 ms
[22_5_2018_15:38:11] {INFO} KERNELCOMM - java.io.FileNotFoundException: \dev\urandom (系统找不到指定的路径。)	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.telegram.bot.kernel.KernelComm.<init>(KernelComm.java:87)
	at org.telegram.bot.kernel.TelegramBot.createKernelComm(TelegramBot.java:146)
	at org.telegram.bot.kernel.TelegramBot.init(TelegramBot.java:95)
	at org.telegram.Deepthought.main(Deepthought.java:57)

[22_5_2018_15:38:11] {INFO} KERNELMAIN - org.telegram.bot.kernel.KernelComm init in 22 ms
[22_5_2018_15:38:11] {INFO} KERNELMAIN - org.telegram.bot.kernel.KernelAuth init in 8 ms
[22_5_2018_15:38:12] {WARNING} TELEGRAMAPI - #1: Creating key
[22_5_2018_15:38:12] {INFO} KERNELMAIN - org.telegram.bot.kernel.KernelComm init in 279 ms
[22_5_2018_15:38:12] {SEVERE} MTPROTO - java.net.SocketException: Connection reset by peer: socket write error	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at org.telegram.mtproto.transport.PlainTcpConnection.writeMessage(PlainTcpConnection.java:67)
	at org.telegram.mtproto.transport.PlainTcpConnection.executeMethod(PlainTcpConnection.java:72)
	at org.telegram.mtproto.pq.Authorizer.executeMethod(Authorizer.java:83)
	at org.telegram.mtproto.pq.Authorizer.authAttempt(Authorizer.java:99)
	at org.telegram.mtproto.pq.Authorizer.doAuth(Authorizer.java:236)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:1041)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:1111)

[22_5_2018_15:38:13] {SEVERE} MTPROTO - java.net.SocketException: Connection reset	at java.net.SocketInputStream.read(SocketInputStream.java:189)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at java.net.SocketInputStream.read(SocketInputStream.java:203)
	at org.telegram.mtproto.transport.PlainTcpConnection.readByte(PlainTcpConnection.java:85)
	at org.telegram.mtproto.transport.PlainTcpConnection.readMessage(PlainTcpConnection.java:45)
	at org.telegram.mtproto.transport.PlainTcpConnection.executeMethod(PlainTcpConnection.java:73)
	at org.telegram.mtproto.pq.Authorizer.executeMethod(Authorizer.java:83)
	at org.telegram.mtproto.pq.Authorizer.authAttempt(Authorizer.java:99)
	at org.telegram.mtproto.pq.Authorizer.doAuth(Authorizer.java:236)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:1041)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:1111)

[22_5_2018_15:38:13] {SEVERE} MTPROTO - java.net.SocketException: Connection reset	at java.net.SocketInputStream.read(SocketInputStream.java:189)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at java.net.SocketInputStream.read(SocketInputStream.java:203)
	at org.telegram.mtproto.transport.PlainTcpConnection.readByte(PlainTcpConnection.java:85)
	at org.telegram.mtproto.transport.PlainTcpConnection.readMessage(PlainTcpConnection.java:45)
	at org.telegram.mtproto.transport.PlainTcpConnection.executeMethod(PlainTcpConnection.java:73)
	at org.telegram.mtproto.pq.Authorizer.executeMethod(Authorizer.java:83)
	at org.telegram.mtproto.pq.Authorizer.authAttempt(Authorizer.java:99)
	at org.telegram.mtproto.pq.Authorizer.doAuth(Authorizer.java:236)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:1041)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:1111)

[22_5_2018_15:38:14] {SEVERE} MTPROTO - java.net.SocketException: Connection reset by peer: socket write error	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:132)
	at org.telegram.mtproto.transport.PlainTcpConnection.<init>(PlainTcpConnection.java:35)
	at org.telegram.mtproto.pq.Authorizer.doAuth(Authorizer.java:227)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:1041)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:1111)

[22_5_2018_15:38:14] {SEVERE} MTPROTO - java.net.SocketException: Connection reset	at java.net.SocketInputStream.read(SocketInputStream.java:189)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at java.net.SocketInputStream.read(SocketInputStream.java:203)
	at org.telegram.mtproto.transport.PlainTcpConnection.readByte(PlainTcpConnection.java:85)
	at org.telegram.mtproto.transport.PlainTcpConnection.readMessage(PlainTcpConnection.java:45)
	at org.telegram.mtproto.transport.PlainTcpConnection.executeMethod(PlainTcpConnection.java:73)
	at org.telegram.mtproto.pq.Authorizer.executeMethod(Authorizer.java:83)
	at org.telegram.mtproto.pq.Authorizer.authAttempt(Authorizer.java:99)
	at org.telegram.mtproto.pq.Authorizer.doAuth(Authorizer.java:236)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:1041)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:1111)

[22_5_2018_15:38:15] {WARNING} TELEGRAMAPI - #1: Timed out
[22_5_2018_15:38:15] {SEVERE} TELEGRAMAPI - org.telegram.api.engine.TimeoutException	at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:1044)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:1111)

[22_5_2018_15:38:16] {WARNING} TELEGRAMAPI - #1: Creating key
[22_5_2018_15:38:16] {SEVERE} MTPROTO - java.net.SocketException: Connection reset by peer: socket write error	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:132)
	at org.telegram.mtproto.transport.PlainTcpConnection.<init>(PlainTcpConnection.java:35)
	at org.telegram.mtproto.pq.Authorizer.doAuth(Authorizer.java:227)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:1041)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:1111)

[22_5_2018_15:38:16] {SEVERE} MTPROTO - java.net.SocketException: Connection reset by peer: socket write error	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:132)
	at org.telegram.mtproto.transport.PlainTcpConnection.<init>(PlainTcpConnection.java:35)
	at org.telegram.mtproto.pq.Authorizer.doAuth(Authorizer.java:227)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:1041)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:1111)

[22_5_2018_15:38:17] {SEVERE} MTPROTO - java.net.SocketException: Connection reset by peer: socket write error	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at org.telegram.mtproto.transport.PlainTcpConnection.writeMessage(PlainTcpConnection.java:67)
	at org.telegram.mtproto.transport.PlainTcpConnection.executeMethod(PlainTcpConnection.java:72)
	at org.telegram.mtproto.pq.Authorizer.executeMethod(Authorizer.java:83)
	at org.telegram.mtproto.pq.Authorizer.authAttempt(Authorizer.java:99)
	at org.telegram.mtproto.pq.Authorizer.doAuth(Authorizer.java:236)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:1041)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:1111)

[22_5_2018_15:38:18] {SEVERE} MTPROTO - java.net.SocketException: Connection reset by peer: socket write error	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at org.telegram.mtproto.transport.PlainTcpConnection.writeMessage(PlainTcpConnection.java:67)
	at org.telegram.mtproto.transport.PlainTcpConnection.executeMethod(PlainTcpConnection.java:72)
	at org.telegram.mtproto.pq.Authorizer.executeMethod(Authorizer.java:83)
	at org.telegram.mtproto.pq.Authorizer.authAttempt(Authorizer.java:99)
	at org.telegram.mtproto.pq.Authorizer.doAuth(Authorizer.java:236)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:1041)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:1111)

[22_5_2018_15:38:20] {SEVERE} MTPROTO - java.net.SocketException: Connection reset by peer: socket write error	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at org.telegram.mtproto.transport.PlainTcpConnection.writeMessage(PlainTcpConnection.java:67)
	at org.telegram.mtproto.transport.PlainTcpConnection.executeMethod(PlainTcpConnection.java:72)
	at org.telegram.mtproto.pq.Authorizer.executeMethod(Authorizer.java:83)
	at org.telegram.mtproto.pq.Authorizer.authAttempt(Authorizer.java:99)
	at org.telegram.mtproto.pq.Authorizer.doAuth(Authorizer.java:236)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:1041)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:1111)

[22_5_2018_15:38:20] {WARNING} TELEGRAMAPI - #1: Timed out
[22_5_2018_15:38:20] {SEVERE} TELEGRAMAPI - org.telegram.api.engine.TimeoutException	at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:1044)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:1111)

[22_5_2018_15:38:21] {WARNING} TELEGRAMAPI - #1: Creating key
[22_5_2018_15:38:22] {SEVERE} MTPROTO - java.net.SocketException: Connection reset	at java.net.SocketInputStream.read(SocketInputStream.java:189)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at java.net.SocketInputStream.read(SocketInputStream.java:203)
	at org.telegram.mtproto.transport.PlainTcpConnection.readByte(PlainTcpConnection.java:85)
	at org.telegram.mtproto.transport.PlainTcpConnection.readMessage(PlainTcpConnection.java:45)
	at org.telegram.mtproto.transport.PlainTcpConnection.executeMethod(PlainTcpConnection.java:73)
	at org.telegram.mtproto.pq.Authorizer.executeMethod(Authorizer.java:83)
	at org.telegram.mtproto.pq.Authorizer.authAttempt(Authorizer.java:99)
	at org.telegram.mtproto.pq.Authorizer.doAuth(Authorizer.java:236)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:1041)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:1111)

[22_5_2018_15:38:23] {SEVERE} MTPROTO - java.net.SocketException: Connection reset	at java.net.SocketInputStream.read(SocketInputStream.java:189)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at java.net.SocketInputStream.read(SocketInputStream.java:203)
	at org.telegram.mtproto.transport.PlainTcpConnection.readByte(PlainTcpConnection.java:85)
	at org.telegram.mtproto.transport.PlainTcpConnection.readMessage(PlainTcpConnection.java:45)
	at org.telegram.mtproto.transport.PlainTcpConnection.executeMethod(PlainTcpConnection.java:73)
	at org.telegram.mtproto.pq.Authorizer.executeMethod(Authorizer.java:83)
	at org.telegram.mtproto.pq.Authorizer.authAttempt(Authorizer.java:99)
	at org.telegram.mtproto.pq.Authorizer.doAuth(Authorizer.java:236)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:1041)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:1111)

[22_5_2018_15:38:24] {SEVERE} MTPROTO - java.net.SocketException: Connection reset	at java.net.SocketInputStream.read(SocketInputStream.java:189)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at java.net.SocketInputStream.read(SocketInputStream.java:203)
	at org.telegram.mtproto.transport.PlainTcpConnection.readByte(PlainTcpConnection.java:85)
	at org.telegram.mtproto.transport.PlainTcpConnection.readMessage(PlainTcpConnection.java:45)
	at org.telegram.mtproto.transport.PlainTcpConnection.executeMethod(PlainTcpConnection.java:73)
	at org.telegram.mtproto.pq.Authorizer.executeMethod(Authorizer.java:83)
	at org.telegram.mtproto.pq.Authorizer.authAttempt(Authorizer.java:99)
	at org.telegram.mtproto.pq.Authorizer.doAuth(Authorizer.java:236)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:1041)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:1111)

[22_5_2018_15:38:25] {SEVERE} MTPROTO - java.net.SocketException: Connection reset	at java.net.SocketInputStream.read(SocketInputStream.java:189)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at java.net.SocketInputStream.read(SocketInputStream.java:203)
	at org.telegram.mtproto.transport.PlainTcpConnection.readByte(PlainTcpConnection.java:85)
	at org.telegram.mtproto.transport.PlainTcpConnection.readMessage(PlainTcpConnection.java:45)
	at org.telegram.mtproto.transport.PlainTcpConnection.executeMethod(PlainTcpConnection.java:73)
	at org.telegram.mtproto.pq.Authorizer.executeMethod(Authorizer.java:83)
	at org.telegram.mtproto.pq.Authorizer.authAttempt(Authorizer.java:99)
	at org.telegram.mtproto.pq.Authorizer.doAuth(Authorizer.java:236)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:1041)
	at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:1111)

